type Query {
  user: ID
  todo(id: String!): Todo
  todos: [Todo!]!
}

type Mutation {
  createUser: Response
  addTodo(title: String!): Response
  updateTodo(id: ID!, title: String, completed: Boolean): Response
  deleteTodo(id: ID!): Response
  dummy: Response
}

type Todo {
  id: ID!
  title: String!
  completed: Boolean!
}

type User {
  id: ID!
  todos: [Todo!]!
}

type Response {
  message: String!
}
