type Query {
  user: ID
  todo(id: String!): Todo
  todos: [Todo!]!
}

type Mutation {
  addTodo(id: ID!, title: String!): Response
  updateTodo(id: ID!, title: String!): Response
  deleteTodo(id: ID!): Response
  dummy: Response
}

type Todo {
  id: ID!
  title: String!
}

union Response = SuccessResponse | ErrorResponse

type SuccessResponse {
  result: Result
}

type ErrorResponse {
  result: Result
  status: Int
  message: String
}

enum Result {
  Success
  Error
}
