import type { NextPage } from "next";
import Head from "next/head";
import { Icon } from "@iconify/react";
import { login } from "~/app/service/auth";
import { useRouter } from "next/router";
import { toast } from "react-toastify";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div data-theme="retro" className="text-primary-content bg-primary">
      <Head>
        <title>TODO βベータ版 | サブスク管理したい</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      {/* <div className="fixed w-full text-center bg-base-100 text-base-content py-2">
        <p>【開発者からのメッセージ】こちらはまだリリース前のサービスです。</p>
        <a className="link" href="https://forms.gle/1Kz5ndKhJdYVakwy7">
          こちらから早期アクセスプログラムに参加できます
        </a>
      </div> */}

      <main className="container mx-auto flex flex-col md:flex-row h-screen w-screen items-center justify-evenly">
        <div>
          <h1 className="text-4xl leading-loose flex gap-2 items-baseli">
            <Icon icon="ri:calendar-todo-line" className="self-center" />
            TODO βベータ版
          </h1>
          <p>GraphQLでTODO管理</p>
        </div>
        <div className="card shadow bg-base-100 text-base-content">
          <div className="card-body gap-3">
            <h2 className="card-title">
              SNSでアカウントを作成できます（無料）
            </h2>
            <button
              className="btn btn-ghost btn-outline gap-6"
              onClick={async () => {
                await login("anonymous");
                toast.success("ログインしました");
              }}
            >
              <Icon icon="raphael:anonymous" width="16" height="16" />
              ゲストで試す
            </button>
            <div
              onClick={() => router.push("/login")}
              className="text-sm flex gap-1 items-center link-hover link"
            >
              他のSNSでもログインできます。→
              <Icon icon="fa-brands:google" />
              <Icon icon="fa-brands:facebook" />
              <Icon icon="fa-brands:github" />
              <Icon icon="fa-brands:twitter" />
            </div>
          </div>
        </div>
      </main>
      {/* <footer className="fixed bottom-0 right-0">@hikaetech</footer> */}
    </div>
  );
};

export default Home;
